// Review Widget
export const FETCH_REVIEWS_START = 'FETCH_REVIEWS_START';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAILED = 'FETCH_REVIEWS_FAILED';
export const SORT_REVIEWS = 'SORT_REVIEWS';
export const VOTE = 'VOTE';